# UCS420 – Cognitive Computing
## Assignment 3: Pandas

Aadish Jain

1024170413

3Q33

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

## Q1. Create the dataset from the given table

The table contains the columns:

- `Tid`
- `Refund`
- `Marital Status`
- `Taxable Income`
- `Cheat`

In [2]:
data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": [
        "Single", "Married", "Single", "Married", "Divorced",
        "Married", "Divorced", "Single", "Married", "Single"
    ],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K", "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

## Q2. Locate rows 0, 4, 7 and 8

`loc` is label-based indexing, so we can directly provide the required row labels.

In [3]:
df.loc[[0, 4, 7, 8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Q3. Navigate the DataFrame

### 1. Select rows from index 3 to 7
Using `iloc[3:8]`, because the stop position is exclusive.

### 2. Select rows from index 4 to 8 and columns 2 to 4
Using `iloc[4:9, 2:5]`.

### 3. Select all rows with column index 1 to 3
Using `iloc[:, 1:4]`. This includes column index 3 because the ending position is exclusive.

In [4]:
# 1. Rows from index 3 to 7
rows_3_to_7 = df.iloc[3:8]
print("1. Rows from index 3 to 7:")
display(rows_3_to_7)

# 2. Rows from index 4 to 8 and columns 2 to 4
rows_4_to_8_cols_2_to_4 = df.iloc[4:9, 2:5]
print("2. Rows from index 4 to 8 and columns 2 to 4:")
display(rows_4_to_8_cols_2_to_4)

# 3. All rows, column index 1 to 3
all_rows_cols_1_to_3 = df.iloc[:, 1:4]
print("3. All rows with column index 1 to 3:")
display(all_rows_cols_1_to_3)

1. Rows from index 3 to 7:

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

2. Rows from index 4 to 8 and columns 2 to 4:

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

3. All rows with column index 1 to 3:

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Q4. Read a CSV file and display its first five rows

The assignment specifies the **Iris dataset from Kaggle**. If `Iris.csv` is not found, the code attempts to download the Kaggle dataset automatically. The included `Iris.csv` lets the notebook run without requiring a Kaggle login or internet connection.

In [5]:
from pathlib import Path
import zipfile
import urllib.request

iris_file = Path("Iris.csv")

# If Iris.csv is not available, try downloading the Kaggle dataset.
if not iris_file.exists():
    kaggle_url = "https://www.kaggle.com/api/v1/datasets/download/uciml/iris"
    zip_file = Path("iris_kaggle.zip")
    try:
        urllib.request.urlretrieve(kaggle_url, zip_file)
        with zipfile.ZipFile(zip_file, "r") as z:
            z.extractall(".")
        print("Iris dataset downloaded from Kaggle.")
    except Exception as e:
        print("Kaggle download was not available:", e)
        print("Please place the downloaded Kaggle Iris.csv in the notebook folder.")

iris_df = pd.read_csv(iris_file)
print("First five rows of Iris dataset:")
display(iris_df.head())

First five rows of Iris dataset:

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0   1            5.1           3.5            1.4           0.2  setosa
1   2            4.9           3.0            1.4           0.2  setosa
2   3            4.7           3.2            1.3           0.2  setosa
3   4            4.6           3.1            1.5           0.2  setosa
4   5            5.0           3.6            1.4           0.2  setosa

## Q5. Delete row 4 and column 3 from the Iris DataFrame

Here, row 4 and column 3 are interpreted as **zero-based DataFrame indices**, as required by typical Pandas `iloc` indexing.

- Delete row index 4.
- Delete column index 3 (`PetalLengthCm` in the Kaggle Iris dataset).

In [6]:
iris_modified = iris_df.drop(index=4)
column_to_delete = iris_modified.columns[3]
iris_modified = iris_modified.drop(columns=column_to_delete)

print(f"Deleted row index: 4")
print(f"Deleted column index: 3 -> {column_to_delete}")
display(iris_modified.head(10))

Deleted row index: 4
Deleted column index: 3 -> PetalLengthCm

    Id  SepalLengthCm  SepalWidthCm  PetalWidthCm Species
0    1            5.1           3.5           0.2  setosa
1    2            4.9           3.0           0.2  setosa
2    3            4.7           3.2           0.2  setosa
3    4            4.6           3.1           0.2  setosa
5    6            5.4           3.9           0.4  setosa
6    7            4.6           3.4           0.3  setosa
7    8            5.0           3.4           0.2  setosa
8    9            4.4           2.9           0.2  setosa
9   10            4.9           3.1           0.1  setosa
10  11            5.4           3.7           0.2  setosa

# Q6. Employee dataset

Create `employees.csv` with the employee information given in the question.

In [7]:
employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

employees_df = pd.DataFrame(employee_data)
employees_df["Joining_Date"] = pd.to_datetime(employees_df["Joining_Date"])

employees_df.to_csv("employees.csv", index=False)
print("employees.csv created successfully.")
display(employees_df)

employees.csv created successfully.

   Employee_ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating
0          101    Alice         HR   29   50000                    4   2020-03-15  Female   5000     4.5
1          102      Bob         IT   34   70000                    8   2017-07-19    Male   7000     4.0
2          103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8
3          104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7
4          105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5

## Q6(a). Shape of the DataFrame

`shape` returns `(number_of_rows, number_of_columns)`.

In [8]:
print("Shape:", employees_df.shape)

Shape: (5, 10)

## Q6(b). Summary of the DataFrame

`info()` displays each column, its data type, and its non-null count.

In [9]:
employees_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      datetime64[ns]
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 532.0+ bytes

## Q6(c). Descriptive statistics

`describe()` gives count, mean, standard deviation, minimum, quartiles, and maximum for numerical columns.

In [10]:
employees_df.describe()

       Employee_ID        Age       Salary  Years_of_Experience         Joining_Date   Bonus    Rating
count     5.000000   5.000000      5.00000             5.000000                    5     5.0  5.000000
mean    103.000000  34.000000  60000.00000             7.400000  2016-08-20 00:00:00  5500.0  4.100000
min     101.000000  28.000000  50000.00000             3.000000  2010-11-25 00:00:00  4500.0  3.500000
25%     102.000000  29.000000  55000.00000             4.000000  2013-06-01 00:00:00  5000.0  3.800000
50%     103.000000  34.000000  60000.00000             8.000000  2017-07-19 00:00:00  5000.0  4.000000
75%     104.000000  38.000000  65000.00000            10.000000  2020-03-15 00:00:00  6000.0  4.500000
max     105.000000  41.000000  70000.00000            12.000000  2021-02-10 00:00:00  7000.0  4.700000
std       1.581139   5.612486   7905.69415             3.847077                  NaN  1000.0  0.494975

## Q6(d). First 5 rows and last 3 rows

In [11]:
print("First 5 rows:")
display(employees_df.head(5))

print("Last 3 rows:")
display(employees_df.tail(3))

First 5 rows:

   Employee_ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating
0          101    Alice         HR   29   50000                    4   2020-03-15  Female   5000     4.5
1          102      Bob         IT   34   70000                    8   2017-07-19    Male   7000     4.0
2          103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8
3          104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7
4          105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5

Last 3 rows:

   Employee_ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating
2          103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8
3          104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7
4          105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5

## Q6(e). Required statistics

1. Average salary
2. Total bonus paid
3. Youngest employee's age
4. Highest performance rating

In [12]:
average_salary = employees_df["Salary"].mean()
total_bonus = employees_df["Bonus"].sum()
youngest_age = employees_df["Age"].min()
highest_rating = employees_df["Rating"].max()

print(f"i. Average salary: ₹{average_salary:,.2f}")
print(f"ii. Total bonus paid: ₹{total_bonus:,.2f}")
print(f"iii. Youngest employee's age: {youngest_age}")
print(f"iv. Highest performance rating: {highest_rating}")

i. Average salary: ₹60,000.00
ii. Total bonus paid: ₹27,500.00
iii. Youngest employee's age: 28
iv. Highest performance rating: 4.7

## Q6(f). Sort by Salary in descending order

In [13]:
employees_sorted = employees_df.sort_values(by="Salary", ascending=False)
display(employees_sorted)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating
1          102      Bob         IT   34   70000                    8   2017-07-19    Male   7000     4.0
2          103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8
4          105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5
3          104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7
0          101    Alice         HR   29   50000                    4   2020-03-15  Female   5000     4.5

## Q6(g). Add a performance category

- **Excellent**: Rating >= 4.5
- **Good**: Rating >= 4.0 and < 4.5
- **Average**: Rating < 4.0

In [14]:
def performance_category(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

employees_df["Performance_Category"] = employees_df["Rating"].apply(performance_category)
display(employees_df)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

## Q6(h). Identify missing values

In [15]:
missing_values = employees_df.isnull().sum()
print("Missing values in each column:")
display(missing_values)

Missing values in each column:

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

## Q6(i). Rename `Employee_ID` to `ID`

In [16]:
employees_df.rename(columns={"Employee_ID": "ID"}, inplace=True)
display(employees_df)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  Gender  Bonus  Rating Performance_Category
0  101    Alice         HR   29   50000                    4   2020-03-15  Female   5000     4.5            Excellent
1  102      Bob         IT   34   70000                    8   2017-07-19    Male   7000     4.0                 Good
2  103  Charlie         IT   41   65000                   10   2013-06-01    Male   6000     3.8              Average
3  104    Diana  Marketing   28   55000                    3   2021-02-10  Female   4500     4.7            Excellent
4  105   Edward      Sales   38   60000                   12   2010-11-25    Male   5000     3.5              Average

## Q6(j). Find employees with:

1. More than 5 years of experience
2. Belonging to the IT department

In [17]:
more_than_5_years = employees_df[employees_df["Years_of_Experience"] > 5]
it_employees = employees_df[employees_df["Department"] == "IT"]

print("i. Employees with more than 5 years of experience:")
display(more_than_5_years)

print("ii. Employees belonging to the IT department:")
display(it_employees)

i. Employees with more than 5 years of experience:

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date Gender  Bonus  Rating Performance_Category
1  102      Bob         IT   34   70000                    8   2017-07-19   Male   7000     4.0                 Good
2  103  Charlie         IT   41   65000                   10   2013-06-01   Male   6000     3.8              Average
4  105   Edward      Sales   38   60000                   12   2010-11-25   Male   5000     3.5              Average

ii. Employees belonging to the IT department:

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date Gender  Bonus  Rating Performance_Category
1  102      Bob         IT   34   70000                    8   2017-07-19   Male   7000     4.0                 Good
2  103  Charlie         IT   41   65000                   10   2013-06-01   Male   6000     3.8              Average

## Q6(k). Add a `Tax` column

The tax amount is 10% of the employee's salary:

`Tax = Salary × 0.10`

In [18]:
employees_df["Tax"] = employees_df["Salary"] * 0.10
display(employees_df)

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

## Q6(l). Save the modified DataFrame

The final DataFrame contains the original data plus `Performance_Category` and `Tax`, and `Employee_ID` has been renamed to `ID`.

In [19]:
output_file = "employees_modified.csv"
employees_df.to_csv(output_file, index=False)

print(f"Modified DataFrame saved successfully as: {output_file}")
display(pd.read_csv(output_file))

Modified DataFrame saved successfully as: employees_modified.csv

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0